### ISSUE TITLE
Ghost2logger not getting installed

### ISSUE THREAD

**Issue by chella2830** [StackStorm-Exchange/stackstorm-ghost2logger#10]
Whether if i use proxy i am getting the above error message. However if i am not using proxy i am getting this error message -
root@ubuntu:/etc/default# st2 pack install ghost2logger

For the "ghost2logger" pack, the following content will be registered:

rules | 0
sensors | 2
triggers | 0
actions | 0
aliases | 0

Installation may take a while for packs with many items.

    [  timeout  ] download pack
ERROR: list index out of range

**Comment by LindsayHill** [comment]
Rather than duplicate issues, let's just track this in one place - https://github.com/StackStorm/st2/issues/3984
