### ISSUE TITLE
Feature: support for list of source IP's (instead of single IP)

### ISSUE THREAD

**Issue by PKedra** [StackStorm-Exchange/stackstorm-ghost2logger#6]
Hello David

First of all - great package. I would like to ask you for new feature... I would like to have option to specify list of IP's instead of single IP for syslog source. This will simplify my life where I want to setup the same RegExp for group of devices.

Maybe someting like this:

  trigger.host:
    pattern: "172.16.10.1; 172.16.10.2; 172.16.10.3 "
    type: eq

**Comment by Kami** [comment]
You should be able to utilize `regex` rule criteria operator for that (instead of using `eq` one) - https://docs.stackstorm.com/rules.html#critera-comparison

**Comment by PKedra** [comment]
@Kami - based on my experience with Ghost2Logger - RegExp will not work for trigger.host.

**Comment by DavidJohnGee** [comment]
@PKedra is correct. A Regular expression will not work for trigger.host. Currently please just use eq.

The core Ghost2logger is being rebuilt and the sensors that provide the linkage to StackStorm will also be rebuilt.

**Comment by DavidJohnGee** [comment]
With the latest PR you can now use a regular expression for the `trigger.host` field. Use criteria match type `eq` or `regex`.
